@startuml Contractor gets images
title Contractor get the sample and live camera image

: Start;
: Check contractor authorization token;
if (Contractor token is provided?) then (yes (Token available in header))
    if (Contractor token is expired?) then (yes)
        : Send HTTP status 401 Token has expired;
        kill
    endif
    ->no;
    if (Facility ID is not valid?) then (yes)
        : Send HTTP status 401 Facility ID is not valid;
        kill
    endif
    ->no;
    if (Start time is not valid?) then (yes)
        : Send HTTP status 401 Token is not yet valid;
        kill
    endif
    ->no;
    if (Token exp is not valid?) then (yes)
        : Send HTTP status 401 exp is not valid;
        kill
    endif
    ->no;
else (no (Token not available in header))
    : Send HTTP status 401 Invalid authorization header format;
    kill
endif
: Validate parameters;
note right
    Taken from the contractor token
    1. facility_id (mandatory)
    2. image_type (mandatory)
end note

: Get facility by facility ID from DB;
if (Facility not found?) then (yes)
    : Send HTTP status 404, Facility not found;
    kill
endif
->no;
if (Image Type) then (CAMERA)
    : Get the console credentials from DB;
    if (Console credentials are empty?) then (yes)
        : Send HTTP status 500, Console credentials are invalid;
        kill
    endif
    ->no;
    #LightSkyBlue:Call GetDirectImage API;
    note left
    Color incicates API call to
     AITRIOS REST API.
    end note
    if (Issue with fetching the device image?) then (yes)
        : Send HTTP status 500, Could not fetch the device image;
        kill
    endif
    ->no;
else (SAMPLE_IMAGE)
    : Get the sample image from the device type object;
    if (Review with rejected status is present for the device ID?) then (yes)
        : Get the review comment;
    endif
    ->no;
endif
: Send HTTP status 200, Return image and rejected comment;

stop
@enduml
