
==== Excel file Data Details

[NOTE]
====
- Filling the Excel template with other than allowed characters, excessive length may result in failure to populate the Database as `caat-helper` does not enforce strict validation of input.
- Even if the Database is populated successfully (with characters that are not allowed, excessive length), the Web Application behavior may not be as expected.
====

===== Sheet1: admin

The `admin` sheet contains following columns.

[%noheader, cols="1,2,2"]
|===
|**Column Name** ^| _login_id_ ^| _admin_password_

|**Description**
| **Mandatory field** +
The unique ID (this column should contain unique values) from which admin can use it for login in Admin app.
| **Mandatory field** +
The admin password to login to the admin app.

|**Character details**
|English AlphaNumeric characters without Space and Japanese Characters except `。` are supported. +
Allowed Special characters are Hyphen `-`, Underscore `_`. +
Length: 1-255 characters.
|Verify password has: +
1. Length: 8-255 characters. +
2. Contains letter from any of 3 categories +
    a. Lowercase (a-z) +
    b. Uppercase (A-Z) +
    c. Digits (0-9) +
    d. Special Characters (`_`, `-`, `!`, `$`, `#`, `%`, `@`) +
3. No space allowed. +

|**Sample Values**
|test-caat-dev
|ajatmd11Arug500TAeCne
|===


[NOTE]
====
* These Admin _login_id_ and _admin_password_ will be the credentials to login to Admin App.
* Admin are created to manage customers.
* One admin can manage multiple customers.
====


===== Sheet2: facility_type

The `facility_type` sheet contains following columns.

[%noheader, cols="3"]
|===
| **Column** ^| _name_ ^| _admin_login_id_
|**Description** | **Mandatory field** +
Contains the facility type name.
| **Mandatory field** +
Verify admin _login_id_ is present in `admin` data

|**Character details**
| English AlphaNumeric characters and Japanese Characters except `。` are supported. +
Allowed Special characters are Space, Hyphen `-`, Underscore `_`. +
Length: 1-127 Characters
|As mentioned in `admin` data

| **Sample Values** | Parking_Type1 | test-caat-dev
|===

[NOTE]
====
* Facility Type table is to declare the types of facilities that customer may have.
* E.g., Parking_Type1, Convenience Store, Garage, Supermarket are few different facility types.
====

===== Sheet3: customer

The `customer` sheet contains following columns.

[%noheader, cols="8"]
|===
| **Column** ^| _customer_name_ ^| _admin_login_id_ ^| _auth_url_ ^| _base_url_ ^| _client_id_ ^| client_secret ^| application_id

| **Description**
| **Mandatory field** +
Customer name
| **Mandatory field** +
Verify admin _login_id_ is present in `admin` data
| **Optional field** +
Add a valid auth URL
| **Optional field** +
Add a valid base URL
| **Optional field** +
Add a valid client ID
| **Optional field** +
Add a valid client secret
| **Optional field** +
Verify application ID is in valid format

|**Character details**
| English AlphaNumeric characters and Japanese Characters except `。` are supported. +
Allowed Special characters are Space, Hyphen `-`, Underscore `_`. +
Length: 1-127 Characters
|As mentioned in `admin` data
|As supported in AITRIOS
|As supported in AITRIOS
|As supported in AITRIOS
|As supported in AITRIOS
|As supported in AITRIOS

| **Sample Values**
| 顧客A
| test-caat-dev
| Example: +
AITRIOS Developer Edition: +
`https://auth.aitrios.sony-semicon.com/oauth2/default/v1/token` (Portal Endpoint) +
AITRIOS Enterprise Edition: +
`https://login.microsoftonline.com/TENANT_ID` (Change the TENANT_ID section)
| Example: +
https://console.aitrios.sony-semicon.com/api/v1
https://console.aitrios.sony-semicon.com/api/v2
| aum12d4cp2jbcfl12112
| df457d4cp2jbcfl12154
| Empty for developer edition and `Application ID` in case of enterprise edition

|===


[NOTE]
====
* Customers are managed by SIer/Admin.
* Each customer can be managed ONLY by a single Admin.
* Usually, each customer will have one AITRIOS Project, AITRIOS Console subscription.
* Customer may buy Developer edition or Enterprise edition of AITRIOS.
* Obtain the console credentials from the AITRIOS portal (Developer edition) or AITRIOS representative (Enterprise edition).
* Console credentials are required to fetch the angle of view from the camera  while contractor is setting the camera at customer premise.
* After adding the customer using caat-helper, updating the `admin_login_id` to that customer is not supported in caat-helper.
* Optional fields in customer sheet can also be populated in Admin App (once the Database is populated).
====


===== Sheet4: device_type

The `device_type` sheet contains following columns.

[%noheader, cols="4"]
|===
| **Column** ^| _name_ ^| _sample_image_path_ ^| _admin_login_id_
| **Description** | **Mandatory field** +
Contains the device type name. | **Mandatory field** +
Path to the sample image.
| **Mandatory field** +
Verify admin _login_id_ is present in `admin` data

|**Character details**
| English AlphaNumeric characters and Japanese Characters except `。` are supported. +
Allowed Special characters are Space, Hyphen `-`, Underscore `_`. +
Length: 1-127 Characters
| Make sure the images are present in the machine that run `caat-helper`. +
Sample image extension can be `.jpeg` or `.jpg` or `.png`. +
Mention the absolute path to the image.
|As mentioned in `admin` data

| **Sample Values**| GarageDevice | /path/to/sample-images/garage.jpeg | test-caat-dev
|===

[NOTE]
====
* Device Type table is to declare the types of devices that will be installed at customer' facilities(premise)
* E.g., Device to be installed at the shop entry/exit, one near the cashier counter, one right in the middle of the shop.
* Sample images are the images that will be displayed in contractor app as reference image  while contractor adjusts the camera angle.
* This tool will only accept sample image data size up to 1MB.
====


===== Sheet5: facility

The `facility` sheet contains following columns.

[%noheader, cols="9"]
|===
| **Column** | _facility_name_ | _prefecture_ | _municipality_ | _effective_start_jst_ | _effective_end_jst_ | _customer_name_ | _facility_type_ | _admin_login_id_
| **Description**   | **Mandatory field** +
Add a valid facility name. | **Mandatory field** +
Add the prefecture where the facility is located | **Mandatory field** +
Add municipality to link to the facility | **Mandatory field** +
Add start time and verify effective start time is a valid date and in the **future** | **Mandatory field** +
Add end time and verify effective end time is a valid date and greater than effective start time | **Mandatory field** +
Add customer name to link to the facility and verify the customer name exists in the `customer` sheet | **Mandatory field** +
Mention the facility type and verify it is present in the facility_type sheet | **Mandatory field** +
Verify admin _login_id_ is present in `admin` data

|**Character details**
3+| English AlphaNumeric characters and Japanese Characters except `。` are supported. +
Allowed Special characters are Space, Hyphen `-`, Underscore `_`. +
Length: 1-127 Characters
2+|Accepted date time format: +
`YYYY-MM-DDTHH:MM:SS+00:00`
|As mentioned in `customer` data
|As mentioned in `facility_type` data
|As mentioned in `admin` data

| **Sample Values** | パーキング1 | 神奈川県  | 厚木市 | 2024-06-28T09:00:00+00:00 | 2024-12-14T09:00:00+00:00 | 顧客A |Parking_Type1 | test-caat-dev
|===


[NOTE]
====
* Facility belongs to a customer.
* Each customer can have as many facilities as needed.
* Facility table consists the details regarding the facility at which the cameras will be installed.
* Facility will have attributes like, location details - Prefecture, Municipality
* After adding the facility using caat-helper, updating the `customer_name` of that facility is not supported in caat-helper.
====

===== Sheet6: device

The `device` sheet contains following columns.

[%noheader, cols="9"]
|===
| **Column** | _device_name_ | _device_id_ | _customer_name_ | _facility_name_ | _device_type_name_ | _facility_prefecture_ | _facility_municipality_ | _admin_login_id_
| **Description** | **Mandatory field** +
Add a valid device name. | **Mandatory field** +
Add a valid device_id | **Mandatory field** +
Add customer name to link to the device and verify the customer name exists in the `customer` sheet | **Mandatory field** +
Add facility name to link to the facility and verify the facility name is present in the `facility` sheet | **Mandatory field** +
Add device type name to link to the device type and verify device type name is present in the `device_type` sheet | **Mandatory field** +
Facility location details - Prefecture | **Mandatory field** +
Facility location details - Municipality | **Mandatory field** +
Verify admin _login_id_ is present in `admin` data


|**Character details**
| English AlphaNumeric characters and Japanese Characters except `。` are supported. +
Allowed Special characters are Space, Hyphen `-`, Underscore `_`. +
Length: 1-127 Characters
|As supported in AITRIOS
|As mentioned in `customer` data
|As mentioned in `facility` data
|As mentioned in `device_type` data
|As mentioned in `facility` data
|As mentioned in `facility` data
|As mentioned in `admin` data


| **Sample Values** | DEVICE_SZP123S_0001 | Aid-00010004-0000-2000-0000-000000000000 | 顧客A | パーキング1 | GarageDevice | 神奈川県 | 厚木市 | test-caat-dev
|===

[NOTE]
====
* _device_name_ can be anything of user choice.
* _device_id_ must match with the ID that is enrolled in AITRIOS Console.
* It is assumed that the device is enrolled to AITRIOS before using the AAT application (by Contractor/Admin).
* Device is linked to facility where it will be installed.
* Following Edge AI Device types are supported:
    ** SZP123S-001
    ** AIH-lVRW2
    ** CSV26
    ** AIH-IPRSW
====
