
== ビルドとデプロイ

=== ソースコードのビルドとデプロイ

* クラウド環境が正常に作成されたら、ソースコードをビルドしてデプロイします。
* バックエンドソースコードはdockerイメージとしてビルドされ、dockerイメージはLightsailコンテナにプッシュされます。管理者アプリとコントラクターアプリのソースコードがビルドされ、S3バケットにアップロードされます。
* `source-build.sh` スクリプトはすべてのソースコードをビルドし、コードへプッシュ・アップロードします。
* 以下のコマンドでビルドデプロイスクリプトを実行します。ビルドとデプロイは10分程度かかる場合があります。

[source,shell]
----
# from tools/cloud-setup/aws
$ bash source-build.sh
----
モジュールのビルドとデプロイが成功すると、Lightsailコンテナ `Images` タブに以下のdocker イメージが表示されます。

イメージ: `aatbackend.caat-backend-service.x`

また、管理者アプリおよびコントラクターアプリ向けに作成されたS3バケットも、両ウェブアプリケーション向けの各CloudFrontディストリビューションと同様確認してください。

* この時点ですべてのサービスはデプロイされます。
* 管理者アプリはログインに使用できますが、コントラクターアプリはデータが入力されるまで使用できません。
* データベースへのデータの入力方法は次の章で説明します。<<db-population-ui, 管理者アプリを使用してデータを入力する>>。


=== アプリのURLを取得

==== 管理者アプリのURLとコントラクターアプリのURL

* 次のコマンドを実行して、管理者アプリのURLとコントラクターアプリのURLを表示します。

[source,shell]
----
# from tools/cloud-setup/aws
$ bash print-app-url.sh
----

ターミナルに表示されたURLをメモしてください。使用方法については次のセクションを参照してください。<<db-population-ui, 管理者アプリを使用してデータを入力する>>。

* 管理者アプリは以下の目的で使用されます
    ** AATツールへのログイン
    ** データベース内のデータの追加/更新/削除
    ** コントラクター用のQRコードの生成
    ** コントラクターによって提出された申請のレビュー

* コントラクターアプリは以下の目的で使用されます。
    ** デバイスのカメラアングルに関する申請を提出する。
