
== Build and Deploy

=== Source Code build and Deploy

* Once the cloud environment is successfully created, build and deploy the source code.
* Backend Source code will be built as docker images, docker images are pushed to Lightsail containers. Admin App and Contractor App source code is built and uploaded to the S3 bucket.
* `source-build.sh` script will build all the source code and push/upload the code.
* Run the Build Deploy Script with the following command. Build and deploy may take around 10 minutes.

[source,shell]
----
# from tools/cloud-setup/aws
$ bash source-build.sh
----

Upon successful build and deployment of modules, following docker image must be seen in Lightsail Container `Images` tab.

Image: `aatbackend.caat-backend-service.x`

In addition, please confirm that the S3 Buckets created for Admin and Contractor app, along with respective CloudFront Distributions for both the web applications..

* At this point, all services are deployed.
* Admin app can be used to log in, however Contractor app can not be used until data is populated.
* Populating the Data into Database in explained in next chapter. <<db-population-ui, Populate Data using Admin App>>.


=== Get Application URLs

==== Admin App URL and Contractor App URL

* Execute the following command to display the Admin App URL and Contractor App URLs

[source,shell]
----
# from tools/cloud-setup/aws
$ bash print-app-url.sh
----

Make note of the displayed URLs in the terminal. Refer following section <<db-population-ui, Populate Data using Admin App>> to know about the usage.

* Admin App is used for following purposes.
    ** Log in to AAT tool.
    ** To add/update/delete the data in the database.
    ** To generate QR codes for the contractors.
    ** To review the applications submitted by contractors.

* Contractor App is used for following purposes.
    ** To submit the applications for camera angle of the devices.
