
== Build and Deploy

=== Source Code build and Deploy

* Once the cloud environment is successfully created, build and deploy the source code.
* Source code will be built as docker images, docker images are pushed to docker registry in Azure cloud.
* `source-build.sh` script will build all the source code and push the docker images to the Azure Container registry.
* Run the Build Deploy Script with the following command. Build and deploy may take around 10 minutes.

[source,shell]
----
# from tools/cloud-setup/azure
$ bash source-build.sh
----

Upon successful build and deployment of docker images, following images must be seen in Container Registry.
Please verify by visiting Azure Portal.

**Container Registry:** crcameratool2024

|====
|Repositories | Description

|caat-backend-service
|Image containing source files of Backend Server

|caat-webadmin
|Image containing build files of Web Admin App

|caat-webapp
|Image containing build files of Web Contractor App

|====

* At this point, all services are deployed.
* Admin app can be used to log in, however Contractor app can not be used until data is populated.
* Populating the Data into Database in explained in next chapter. <<db-population-ui, Populate Data using Admin App>>.


=== Get Application URLs

==== Admin App URL and Contractor App URL

* Execute the following command to display the Admin App URL and Contractor App URLs

[source,shell]
----
# from tools/cloud-setup/azure
$ bash print-app-url.sh
----

Make note of the displayed URLs in the terminal. Refer following section <<db-population-ui, Populate Data using Admin App>> to know about the usage.

* Admin App is used for following purposes.
    ** Log in to AAT tool.
    ** To add/update/delete the data in the database.
    ** To generate QR codes for the contractors.
    ** To review the applications submitted by contractors.

* Contractor App is used for following purposes.
    ** To submit the applications for camera angle of the devices.
