
== よくある質問

Q: セットアップスクリプトを使用したAATアプリケーションのデプロイに必要な前提条件とは？::
A: セットアップスクリプトを使用してAATアプリケーションをデプロイする前に、以下の前提条件を確認してください。:
    * リソースの作成に必要な権限つきのAzureサブスクリプションが有効であること。
    * シェルスクリプトを実行するためのローカルマシンにAzure CLIがインストールされていること。
    * リソースグループ、仮想ネットワーク、アプリサービス、データベースなどの基本的なAzureコンセプトに関する知識があること。

Q: 特定のニーズに合わせたARMテンプレートのカスタマイズは可能ですか?::
A: はい、ARMテンプレートのカスタマイズは可能です。但し `tools/cloud-setup/scripts/azure/arm-template-caat.json` への変更は慎重にお願いします。

Q: スクリプトを使用して作成したクラウドインスタンスの削除はどうすればいいですか?::
A: クラウドインスタンスを削除するためのスクリプトはありません。作成されたリソースをすべて削除するには、Azureポータルを開いてリソースグループを削除します。

Q: AATアプリケーションに他のセキュリティ設定を適用することはできますか?::
A: はい、Microsoft DefenderやApplication Gatewayなどの他のセキュリティ設定を適応することができます。但し、提供されたクラウドスクリプトはそのような操作をサポートしていません。そのため、Azureポータル内で手動で変更するか、カスタムスクリプトを作成してください。

Q: デプロイメント中の一般的なエラーのトラブルシューティングはどうすればいいですか?::
A: デプロイメント中にエラーが発生した場合は:
    * Azure CLIアウトプットか、特定のエラーメッセージのデプロイメントログを確認してください。
    * 必要なパラメーターがすべて正しく提供され、フォーマットされていることを確認してください
    * Azureサービスのステータスや所在地にサービスがあるかどうかを確認してください。
    * 特定のエラーに関するトラブルシューティングのガイダンスは、Azureマニュアルおよびコミュニティフォーラムをご確認ください。


Q: 管理者パスワードのリセットするにはどうすればいいですか ?::
A: caatヘルパーを使用して、ログインIDを提示することで管理者パスワードをリセットすることができます。 +

以下のコマンドを使用して管理者やそのログインIDをリストにします。

[source,shell]
----
(.venv) $ caat-helper db list-admin
----

パスワードのリセットには以下のコマンドを使用します

[source,shell]
----
(.venv) $ caat-helper db reset-pass --login-id {admin-login-id} --password {new-pasword-value}
----

Q: データベースからデータを消去して再度スタートする場合、または間違った詳細を入力した場合はどうすればいいですか？?::
A: caatヘルパーを使用して、データベースからすべてのデータを一度に削除できます。 +
現段階で、caatヘルパーは選択したデータのみの消去には対応していません。

データベースをクリアするには、以下のコマンドを使用します。

[source,shell]
----
(.venv) $ caat-helper db clear
----

Q: セットアップ後にデータベース操作を実行するため、データベースのホストマシンIPアドレスをホワイトリストに登録するにはどうすればいいですか ?::
A: `allow-host-ip-db.sh`スクリプトを使用することで、ホストマシンIPアドレスをホワイトリストに登録できます。 +

[source,shell]
----
# from tools/cloud-setup/scripts
$ bash allow-host-ip-db.sh
----
