// = Angle Adjustment Tool (AAT)
:docinfo: shared
:doctype: book
:data-uri:
:title: AAT API Workflow
:toc: left
:toclevels: 3
:sectanchors:
:sectlinks:
:sectnums:
:multipage-level: 2


== API Workflow

=== Admin API workflow

==== Admin Login

plantuml::api-workflow/api-admin/admin-login.puml[]

==== Create admin

plantuml::api-workflow/api-admin/admin-create-admin.puml[]

==== Create customer

plantuml::api-workflow/api-admin/admin-create-customer.puml[]

==== Get customer list

plantuml::api-workflow/api-admin/admin-get-customer-list.puml[]

==== Get customer details by ID

plantuml::api-workflow/api-admin/admin-get-customer-details.puml[]

==== Update customer console credentials

plantuml::api-workflow/api-admin/admin-updates-console-creds.puml[]

==== Get device types

plantuml::api-workflow/api-admin/admin-get-device-types.puml[]

==== Get device type by ID

plantuml::api-workflow/api-admin/admin-get-device-type-by-id.puml[]

==== Create device type

plantuml::api-workflow/api-admin/admin-create-device-type.puml[]

==== Update device type

plantuml::api-workflow/api-admin/admin-update-device-type.puml[]

==== Get facility types

plantuml::api-workflow/api-admin/admin-get-facility-types.puml[]

==== Create facility type

plantuml::api-workflow/api-admin/admin-create-facility-type.puml[]

==== Get facilities by customer

plantuml::api-workflow/api-admin/admin-get-facilities-by-customer.puml[]

==== Create or update facility

plantuml::api-workflow/api-admin/admin-create-or-update-facility.puml[]

==== Get facility details

plantuml::api-workflow/api-admin/admin-get-facility-details.puml[]

==== Get combined devices

plantuml::api-workflow/api-admin/admin-get-combined-devices.puml[]

==== Get device connection state

plantuml::api-workflow/api-admin/admin-get-device-status.puml[]

==== Save or update devices

plantuml::api-workflow/api-admin/admin-save-update-devices.puml[]

==== Bulk delete devices

plantuml::api-workflow/api-admin/admin-bulk-delete-devices.puml[]

==== Generate customer QR codes

plantuml::api-workflow/api-admin/admin-generate-customer-qr-codes.puml[]

==== Delete reviews by device

plantuml::api-workflow/api-admin/admin-delete-reviews-by-device.puml[]

==== Get latest reviews

plantuml::api-workflow/api-admin/admin-get-latest-reviews.puml[]

==== Get reviews history

plantuml::api-workflow/api-admin/admin-get-review-history.puml[]

==== Get review by ID

plantuml::api-workflow/api-admin/admin-get-review-by-id.puml[]

==== Update review by ID

plantuml::api-workflow/api-admin/admin-approve-or-reject-review-by-id.puml[]

==== Export data

plantuml::api-workflow/api-admin/admin-export-data.puml[]

==== Import data

plantuml::api-workflow/api-admin/admin-import-data.puml[]

=== Contractor API workflow

==== Contractor Authorize

plantuml::api-workflow/api-contractor/contractor-auth.puml[]

==== Get facility devices

plantuml::api-workflow/api-contractor/contractor-get-facility-devices.puml[]


==== Get camera / reference image by device ID

plantuml::api-workflow/api-contractor/contractor-get-images.puml[]


==== Get device status

plantuml::api-workflow/api-contractor/contractor-gets-device-status.puml[]


==== Create review

plantuml::api-workflow/api-contractor/contractor-create-review.puml[]
