@startuml Admin getting facility details
title Get Facility Details By Facility ID

: Start;
if (Auth token is provided?) then (yes)
    if (Auth token is not valid or expired?) then (yes)
        :Send HTTP status 401,
        Auth token is invalid or token expired;
        kill
    endif
else (no)
    : Send HTTP status 401, unauthorized;
    kill
endif
->no(valid token);
: Validate parameters;
note right
    facility_id (mandatory)
end note
if (Parameters are not valid?) then (yes)
    : Send HTTP status 400 error;
    kill
endif
->no;
: Get facility by ID from the DB;
if (Facility does not exist?) then (yes)
    : Send HTTP status 404, Facility not found;
    kill
endif
->no;
if (Facility is not associated with the current user/admin?) then (yes)
    : Send HTTP status 403, Permission denied;
    kill
endif
->no;
: Retrieve facility details from the DB;
: Send HTTP status 200 with facility details as the response;
stop
@enduml
